
version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      DOCKER_HOST: localhost:8080

      POSTGRES_DB: httpstorage
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: go
    # build the Dockerfile, alternatively use an image.
    build:
      context: .
    depends_on:
      - "postgres"

volumes:
  dbdata: # create the volume for persisting data.